---
services:
  cde_demo:
    image: ghcr.io/pgodschalk/cde-demo:${DOCKER_IMAGE_TAG:-latest}
    build:
      cache_from:
        - ghcr.io/pgodschalk/cde-demo:${DOCKER_IMAGE_TAG:-latest}
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./cde_demo:/usr/src/app/cde_demo
    restart: always
