name: CDE Demo

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/apps_cde_demo.yml'
      - 'cde_demo/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/apps_cde_demo.yml'
      - 'cde_demo/**'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authorize Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/pgodschalk/cde-demo
          tags: |
            type=sha,prefix=
            type=raw,value=${{ github.event.pull_request.head.sha }},event=pr
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.description=Demo of running a Django app in a CDE
            org.opencontainers.image.title=cde-demo

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
